version: "3.3"
services:
  scheduler:
    build:
      context: ./services/scheduler
      dockerfile: Dockerfile.dev
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/scheduler/:/usr/src/app/
    restart: always
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - redis
    links:
      - redis:redis

  redis:
    image: redis:6.0.5-alpine
    volumes:
      - redis_data:/var/lib/redis

  celery_worker:
    build:
      context: ./services/scheduler
      dockerfile: Dockerfile.dev
    command: celery -A celery_worker.celery worker --loglevel=INFO
    volumes:
      - ./services/scheduler/:/usr/src/app/
    depends_on:
      - redis

  celery-beat:
    build:
      context: ./services/scheduler
      dockerfile: Dockerfile.dev
    command: celery -A celery_worker.celery beat --loglevel=INFO
    volumes:
      - ./services/scheduler/:/usr/src/app/
    depends_on:
      - redis

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:
      - 8888:8888

volumes:
  redis_data:
